### ISSUE TITLE
Can you support macOS?

### ISSUE THREAD

**Issue by a7a2** [go-freebsd/pf#1]
Can you support macOS?

**Comment by threez** [comment]
Actually, I started with macOS one year ago. I dropped development on that as there are multiple issues:

1. Using the syscall/ioctl interface is considered a private API on macOS. They suggest using the pfctl command
2. The pf headers need to be copied manually into the project, from the Darwin sources, they are not part of the regular macOS distribution
3. The pf version of the mac is rather old and is not source or binary compatible with the one from FreeBSD
